### PR TITLE
uwu owo mrrp meow

### PR DESCRIPTION
**Pull request by apozjebus**
This pull request includes several changes to the project setup and configuration files, as well as the addition of a new `app.js` file to set up an Express.js application. The most important changes include the addition of a new Express.js application setup, updates to the `.idea` project configuration files, and the inclusion of JavaScript library mappings.

### Express.js Application Setup:
* [`24_10_21/app.js`](diffhunk://#diff-93032ff01a8553e1adad6c95b15c9a364dfc273e0a723a1964b35ad6e97681b6R1-R46): Added a new file to set up an Express.js application, including middleware for logging, parsing cookies, and handling static files, as well as routing and error handling.

### Project Configuration Updates:
* [`24_10_21/.idea/.gitignore`](diffhunk://#diff-50b6770de37f3c9a12b5ab7a3bfacd5fe59e0a05753a963bd9c8aa952cde7d76R1-R5): Added default ignored files for the project, including `shelf/`, `workspace.xml`, and `httpRequests/`.
* [`24_10_21/.idea/24_10_23.iml`](diffhunk://#diff-d6681312bb4e260794c2243c935d7bb0d8cd8aef375d502c761bd8bbd1eadfc4R1-R12): Added a new module configuration file with excluded folders and source folder settings.
* [`24_10_21/.idea/modules.xml`](diffhunk://#diff-a036125d34fbd24d3aba5a5823125d866fd64bddc219b3bea83f488505627c12R1-R8): Added a new project module manager configuration file to include the new module.
* [`24_10_21/.idea/vcs.xml`](diffhunk://#diff-61d433241006925dcfc72628aed4ca44eb07e06e54b05653ef94728c0de91006R1-R6): Added a new VCS directory mappings configuration file to map the project directory to Git.

### JavaScript Library Mappings:
* [`24_10_21/.idea/jsLibraryMappings.xml`](diffhunk://#diff-006894bedf4e45249f9a55eca18f41fe63ff622d6c920dc992653ae265fb1de1R1-R6): Added a new JavaScript library mappings configuration file to include the Node.js Core library.

### Run Configuration:
* [`24_10_21/.idea/runConfigurations/bin_www.xml`](diffhunk://#diff-29fa796f987819991edc3d647e02366d1934b9b74649c1143cbf5128d60fb6a0R1-R11): Added a new run configuration for the `bin/www` file with environment variables and browser settings.

### CODE REVIEW

**Comment by Majdanka** [comment]
halo halo, mati merguj

**Comment by Majdanka** [comment]
matts

**Comment by apozjebus** [comment]
no niestety widzowie:<<

**Comment by Majdanka** [comment]
halo mati merguj

**Comment by xAkre** [comment]
Vote merge

**Comment by xAkre** [comment]
5 votow i mergujesz @eWarzywo

**Comment by Majdanka** [comment]
na 5 voteow uncloseujesz i mergujesz

**Pull request closed without merging**
